export const data = {
	irina: {
		name: 'Ирина Лайм',
		description: 'преподаватель по робототехнике',
		img: './public/images/irina.jpg',
		education:
			'Ирина Лайм education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Ирина Лайм education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Ирина Лайм education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Ирина Лайм education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Ирина Лайм education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Ирина Лайм education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
		experience:
			'Ирина Лайм experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Ирина Лайм experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Ирина Лайм experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Ирина Лайм experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Ирина Лайм experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Ирина Лайм experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
		awards:
			'Ирина Лайм awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Ирина Лайм awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Ирина Лайм awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Ирина Лайм awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Ирина Лайм awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Ирина Лайм awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
	},
	marina: {
		name: 'Марина Орлова',
		description: 'преподаватель по робототехнике',
		img: './public/images/marina.jpg',
		education:
			'Марина Орлова education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Марина Орлова education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Марина Орлова education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Марина Орлова education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Марина Орлова education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Марина Орлова education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
		experience:
			'Марина Орлова experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Марина Орлова experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Марина Орлова experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Марина Орлова experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Марина Орлова experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Марина Орлова experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
		awards:
			'Марина Орлова awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Марина Орлова awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Марина Орлова awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Марина Орлова awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Марина Орлова awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Марина Орлова awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
	},
	maxim: {
		name: 'Максим Петров',
		description: 'преподаватель по программированию',
		img: './public/images/maxim.jpg',
		education:
			'Максим Петров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Максим Петров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Максим Петров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Максим Петров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Максим Петров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Максим Петров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
		experience:
			'Максим Петров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Максим Петров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Максим Петров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Максим Петров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Максим Петров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Максим Петров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
		awards:
			'Максим Петров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Максим Петров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Максим Петров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Максим Петров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Максим Петров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Максим Петров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
	},
	konstantin: {
		name: 'Константин Назаров',
		description: 'преподаватель по робототехнике',
		img: './public/images/konstantin.jpg',
		education:
			'Константин Назаров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Константин Назаров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Константин Назаров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Константин Назаров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Константин Назаров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Константин Назаров education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
		experience:
			'Константин Назаров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Константин Назаров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias, Константин Назаров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Константин Назаров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias, Константин Назаров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Константин Назаров experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias',
		awards:
			'Константин Назаров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Константин Назаров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Константин Назаров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Константин Назаров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!, Константин Назаров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Константин Назаров awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
	},
	liza: {
		name: 'Лиза Весенняя',
		description: 'преподаватель по программированию',
		img: './public/images/liza.jpg',
		education:
			'Лиза Весенняя education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя education Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
		experience:
			'Лиза Весенняя experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя experience Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
		awards:
			'Лиза Весенняя awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias! Лиза Весенняя awards Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut minus, ratione asperiores corporis eveniet labore, vero doloremque, beatae pariatur dignissimos est aspernatur molestiae ex perspiciatis excepturi placeat similique. Reiciendis, molestias!',
	},
};
